pub mod exec;
pub mod info;
pub mod io;

use jni::sys::{jbyte, jshort};

pub type ClassConstIndex = u16;

#[derive(Copy, Clone, Debug)]
pub enum PrimitiveType {
    Boolean,
    Char,
    Float,
    Double,
    Byte,
    Short,
    Int,
    Long,
}

//noinspection SpellCheckingInspection
#[allow(non_camel_case_types)]
#[derive(Debug, Clone)]
pub enum Instruction {
    aaload,
    aastore,
    aconst_null,
    aload(u16),
    anewarray(ClassConstIndex),
    areturn,
    arraylength,
    astore(u16),
    athrow,
    baload,
    bastore,
    bipush(jbyte),
    caload,
    castore,
    checkcast(ClassConstIndex),
    d2f,
    d2i,
    d2l,
    dadd,
    daload,
    dastore,
    dcmpg,
    dcmpl,
    dconst_0,
    dconst_1,
    ddiv,
    dload(u16),
    dmul,
    dneg,
    drem,
    dreturn,
    dstore(u16),
    dsub,
    dup,
    dup_x1,
    dup_x2,
    dup2,
    dup2_x1,
    dup2_x2,
    f2d,
    f2i,
    f2l,
    fadd,
    faload,
    fastore,
    fcmpg,
    fcmpl,
    fconst_0,
    fconst_1,
    fconst_2,
    fdiv,
    fload(u16),
    fmul,
    fneg,
    frem,
    freturn,
    fstore(u16),
    fsub,
    getfield(ClassConstIndex),
    getstatic(ClassConstIndex),
    goto(i16),
    goto_w(i32),
    i2b,
    i2c,
    i2d,
    i2f,
    i2l,
    i2s,
    iadd,
    iaload,
    iand,
    iastore,
    iconst_m1,
    iconst_0,
    iconst_1,
    iconst_2,
    iconst_3,
    iconst_4,
    iconst_5,
    idiv,
    if_acmpeq(i16),
    if_acmpne(i16),
    if_icmpeq(i16),
    if_icmpne(i16),
    if_icmplt(i16),
    if_icmpge(i16),
    if_icmpgt(i16),
    if_icmple(i16),
    ifeq(i16),
    ifne(i16),
    iflt(i16),
    ifge(i16),
    ifgt(i16),
    ifle(i16),
    ifnonnull(i16),
    ifnull(i16),
    iload(u16),
    imul,
    ineg,
    instanceof(ClassConstIndex),
    invokespecial(ClassConstIndex),
    invokestatic(ClassConstIndex),
    invokevirtual(ClassConstIndex),
    ior,
    irem,
    ireturn,
    ishl,
    ishr,
    istore(u16),
    isub,
    iushr,
    ixor,
    jsr(i16),
    jsr_w(i32),
    l2d,
    l2f,
    l2i,
    ladd,
    laload,
    land,
    lastore,
    lcmp,
    lconst_0,
    lconst_1,
    ldc(u8),
    ldc_w(u16),
    ldc2_w(u16),
    ldiv,
    lload(u16),
    lmul,
    lneg,
    lor,
    lrem,
    lreturn,
    lshl,
    lshr,
    lstore(u16),
    lsub,
    lushr,
    lxor,
    monitorenter,
    monitorexit,
    multianewarray {
        index: ClassConstIndex,
        dimensions: u8,
    },
    new(ClassConstIndex),
    newarray(PrimitiveType),
    nop,
    pop,
    pop2,
    putfield(ClassConstIndex),
    putstatic(ClassConstIndex),
    ret(u16),
    r#return,
    saload,
    sastore,
    sipush(jshort),
    swap,
    invokeinterface {
        index: ClassConstIndex,
        count: u8,
    },
    iinc {
        index: u16,
        const_inc: i16,
    },
    lookupswitch {
        default_offset: i32,
        match_offset: Vec<(i32, i32)>,
    },
    tableswitch {
        default_offset: i32,
        low: i32,
        jump_offsets: Vec<i32>,
    },
    invokedynamic(ClassConstIndex),
}
