[package]
name = "java_std"
version = "0.1.0"
edition = "2018"
autobins = false

[lib]
name = "rustyjvm"
crate-type = ["cdylib"]

[dependencies]
#jvm = { path = "../jvm" }
jni = "0.19.0"


[build-dependencies]
walkdir = "2.3.2"
