[env]
CARGO_MAKE_EXTEND_WORKSPACE_MAKEFILE = true

# Put a bandaid on the stack size problem instead of trying to fix it
#RUSTFLAGS = "-C link-args=-Wl,-zstack-size=67108864"
#RUSTFLAGS = "-C link-args=-Wl,--version-script=/mnt/c/Users/Jasper/CLionProjects/JavaClassTests/java_std/test-mapfile"

[config]
default_to_workspace = false

[tasks.test-run]
toolchain = "nightly"
command = "cargo"
args = ["run", "--release", "-p", "java", "--", "-v", "Medium"]
dependencies = ["build"]

[tasks.test-run.windows]
toolchain = "nightly-i686-pc-windows-msvc"

[tasks.build]
toolchain = "nightly"
command = "cargo"
args = ["build", "--release", "-p", "rust_jvm"]

[tasks.build.windows]
toolchain = "nightly-i686-pc-windows-msvc"
