[env]
CARGO_MAKE_EXTEND_WORKSPACE_MAKEFILE = true
#RUSTFLAGS = "-C link-args=-Wl,--version-script=/mnt/c/Users/Jasper/CLionProjects/JavaClassTests/java_std/test-mapfile"

[config]
default_to_workspace = false

[tasks.test-run]
toolchain = "nightly"
command = "cargo"
args = ["run", "--release", "--bin", "java", "--", "-v", "Simple"]
dependencies = ["build"]

[tasks.test-run.windows]
toolchain = "nightly-i686-pc-windows-msvc"

[tasks.build]
toolchain = "nightly"
command = "cargo"
args = ["rustc", "--release", "-p", "java_std", "--", "-C", "-save-temps", "-C", "link-args=-Wl,--version-script=/mnt/c/Users/Jasper/CLionProjects/JavaClassTests/java_std/test-mapfile"]
#args = ["build", "--release", "-p", "java_std"]

[tasks.build.windows]
toolchain = "nightly-i686-pc-windows-msvc"
