[env]
CARGO_MAKE_EXTEND_WORKSPACE_MAKEFILE = true
#RUSTFLAGS = "-C link-args=-Wl,--version-script=/mnt/c/Users/Jasper/CLionProjects/JavaClassTests/java_std/test-mapfile"

[config]
default_to_workspace = false

[tasks.test-run]
toolchain = "nightly"
command = "cargo"
args = ["run", "-p", "java", "--", "-v", "Simple"]
dependencies = ["build"]

[tasks.test-run.windows]
toolchain = "nightly-i686-pc-windows-msvc"

[tasks.build]
toolchain = "nightly"
command = "cargo"
args = ["build", "-p", "java_std"]

[tasks.build.windows]
toolchain = "nightly-i686-pc-windows-msvc"
