/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class Testing */

#ifndef _Included_Testing
#define _Included_Testing
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     Testing
 * Method:    testA
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_Testing_testA
  (JNIEnv *, jobject);

/*
 * Class:     Testing
 * Method:    testB
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_Testing_testB__
  (JNIEnv *, jobject);

/*
 * Class:     Testing
 * Method:    testB
 * Signature: (Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_Testing_testB__Ljava_lang_String_2
  (JNIEnv *, jobject, jstring);

/*
 * Class:     Testing
 * Method:    testB
 * Signature: ([B)I
 */
JNIEXPORT jint JNICALL Java_Testing_testB___3B
  (JNIEnv *, jobject, jbyteArray);

/*
 * Class:     Testing
 * Method:    testB
 * Signature: (Ljava/lang/String;[[[BLjava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_Testing_testB__Ljava_lang_String_2_3_3_3BLjava_lang_String_2
  (JNIEnv *, jobject, jstring, jobjectArray, jstring);

/*
 * Class:     Testing
 * Method:    ___testC___
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_Testing__1_1_1testC_1_1_1
  (JNIEnv *, jobject);

/*
 * Class:     Testing
 * Method:    ___test___D___
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_Testing__1_1_1test_1_1_1D_1_1_1__
  (JNIEnv *, jobject);

/*
 * Class:     Testing
 * Method:    ___test___D___
 * Signature: (III)J
 */
JNIEXPORT jlong JNICALL Java_Testing__1_1_1test_1_1_1D_1_1_1__III
  (JNIEnv *, jobject, jint, jint, jint);

/*
 * Class:     Testing
 * Method:    test_00024F
 * Signature: (III)I
 */
JNIEXPORT jint JNICALL Java_Testing_test_00024F
  (JNIEnv *, jobject, jint, jint, jint);

#ifdef __cplusplus
}
#endif
#endif
