/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class jvm_hooks_PrintStreamHook */

#ifndef _Included_jvm_hooks_PrintStreamHook
#define _Included_jvm_hooks_PrintStreamHook
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     jvm_hooks_PrintStreamHook
 * Method:    sendIO
 * Signature: (ILjava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_jvm_hooks_PrintStreamHook_sendIO
  (JNIEnv *, jobject, jint, jstring);

#ifdef __cplusplus
}
#endif
#endif
