[package]
name = "java"
version = "0.1.0"
authors = ["Jasper Meggitt <jasper.meggitt@gmail.com>"]
edition = "2021"

[features]
default = []
profile = []

[dependencies]
jni = "0.19.0"
log = "0.4.14"
shell-words = "1.0.0"
hashbrown = "0.11.2"
glob = "0.3.0"
libloading = "*"
